### PR TITLE
types: enable @typescripteslint/array-type

### PR DESCRIPTION
**Pull request by LoTwT**
## description

[`@typescripteslint/array-type`](https://typescript-eslint.io/rules/array-type) is an eslint rule to unify the array type styles.

### CODE REVIEW

**Comment by chouchouji** [comment]
Thanks for your contribution. 

The rule of this eslint plugin is 
image

So for union type, Array is better T 

image

**Comment by chouchouji** [comment]
I think you can check this eslint plugin docs and update code. Thanks again.

**Comment by LoTwT** [comment]
🤣 I enable this rule, but indeed, the final preferred style isn't decided by me.

♥️ From #31, @haoziqaq didn't show his preferred style, and @chouchouji you prefer `array-simple`. So We can wait for @haoziqaq's choice.

**Comment by chouchouji** [comment]
> 🤣 I enable this rule, but indeed, the final preferred style isn't decided by me.
> 
> ♥️ From #31, @haoziqaq didn't show his preferred style, and @chouchouji you prefer `array-simple`. So We can wait for @haoziqaq's choice.

I think the default behavior of this eslint plugin is better. 
image

**Review by haoziqaq — APPROVED** [review]

**Pull request merged**
